### ISSUE TITLE
Render function of Tabs is missing a key

### ISSUE THREAD

**Issue by prathadsan** [StevenIseki/react-tab-view#2]
When using the package, a warning is thrown constantly with the following message:
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Tabs. See https://fb.me/react-warning-keys for more information.

As far as I am concerned, there is a key missing for the render function in tabs.js
I have tried to include a key and it worked. 

Could this issue please be fixed ?

**Comment by StevenIseki** [comment]
Hey it should be all fixed now, I just had to add in `key: i` on line 56 in the [tabs.js file](https://github.com/StevenIseki/react-tab-view/blob/d4242b3cba45b555549bd19f529901e7749b996e/src/tabs.js) I should probably rewrite the `/src` to use es6 as it is a bit unclear using raw react in the src.
