### ISSUE TITLE
Not showing up as Tabs

### ISSUE THREAD

**Issue by stallter4** [StevenIseki/react-tab-view#4]
I had the following code which is being mounted in flow router.  I just got an unordered list of "heading1"," heading2", then two paragraphs of "This is the first tab's content", and "This is the second tab's content", but no tabs.  I was really looking for a nice lightweight tab component like this.  I wish it would have worked.  

import { Tabs, Tab } from 'react-tab-view';
import React, { Component, PropTypes } from 'react'

TabComponent = React.createClass({

    render() {
        return(
        <div>
            <Tabs headers={['heading 1', 'heading 2']}>
                <Tab>
                    <p>This is the first tab's content</p>
                </Tab>
                <Tab>
                    <p>This is the second tab's content</p>
                </Tab>
            </Tabs>
        </div>
    );
    }

});

**Comment by StevenIseki** [comment]
Hi @stallter4 you will have to add some basic styles for the tabs. I could add some styles in jsx or add the option to pass in jsx styles in the future but for now styling the classes as shown [here](https://github.com/StevenIseki/react-tab-view/blob/master/example/public/tabs.css) will fix the issue.

**Comment by stallter4** [comment]
Nice, this is good thanks..
