### ISSUE TITLE
can't accept other react components inside a tab. 

### ISSUE THREAD

**Issue by stallter4** [StevenIseki/react-tab-view#5]
I have a react component: 

    import React from 'react';
    var ReactDom = require('react-dom');

    Drawing = React.createClass({

    componentDidMount: function() {
        var el = ReactDom.findDOMNode(this); // This is de div we are rendering
        var svg = d3.select(el)
            .append("svg");
            //.attr("viewBox", "0 0 100 100")
            //.attr("preserveAspectRatio", "xMidYMid meet");
        var circleSelection = svg.append("circle")
              .attr("cx", 25)
              .attr("cy", 25)
              .attr("r", 25)
              .style("fill", "purple");
    },

    render: function() {

        return (
            <div className="drawing" style={{"border":"1px solid black"}}></div>
        );
    }
    });

If I try to insert it in a tab structure like this:

    render() {
        return (
            <Tabs headers ={["Drawing", "Import", "Color Legend", "Tube Sheet", "3D", "Report"]} >
                <Tab >
                    <div className="buttons">
                        <button>
                            Fun
                        </button>
                        <button>
                            Move
                        </button>
                    </div>
                    <Drawing />
                </Tab>
                <Tab>
                    <h1>Import</h1>
                </Tab>
                <Tab >
                    <h1>Color Legend</h1>
                </Tab>
                <Tab >
                    <h1>Tube Sheet</h1>
                </Tab>
                <Tab>
                    <h1>3D</h1>
                </Tab>
                <Tab>
                    <h1>Report</h1>
                </Tab>
            </Tabs>
        );
    }

I get this Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `Tab`, expected `object`.
    in Tab 

The component works elsewhere without error.  I even broke down the Drawing react component so it only returned a div and it was still putting out this warning.

**Comment by stallter4** [comment]
wait.. I found it out.  Your Tab need everything to be in one element.  Man, you should really document my last two issues in your Readme.  I love this lightweight tab, and I have a lot of control of the styling.  I'm making good use of this.  Thanks.

**Comment by StevenIseki** [comment]
Hey thanks for mentioning this issue, I think the prop type needed to change to `node` instead of `object` to fix the issue. It should be working without the warning now in `version 1.0.5`. Feel free to make some updates and open up a pr if you find a fix or an improvement.
